baseURL = "https://metal.trennds.com/"
languageCode = "en-us"
title = "Metal UI"
assetDir="../scss/"

[permalinks]
  blog = "blog/:filename/"
  posts = "post/:filename/"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Build responsive, mobile-first projects on the web with the world’s most popular front-end component library."

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Posts"
    pre = "edit"
    url = "/posts/"
    weight = 2

[taxonomies]
  tag = "tags"
